// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rguxltrveizbghlqmhhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJndXhsdHJ2ZWl6YmdobHFtaGhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwMzQxMjMsImV4cCI6MjA5MTYxMDEyM30.et_qHoqMwRHqfxvBExnuoelJ0UfHzOT758186oDudBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});